/**
 * Artillery processor — real Ed25519 challenge-response auth per virtual
 * user (common/middleware/auth.ts), not a bearer token pasted into the
 * script. Each VU registers its own participant, requests a challenge,
 * signs it, and authenticates for real — the same flow a real wallet
 * integration goes through, so the load test exercises the actual auth
 * path instead of skipping it.
 *
 * Signing detail that matters (see TECHNICAL_WHITEPAPER.md section 6):
 * the server verifies against the UTF-8 bytes of the challenge *string*
 * itself (auth.ts: `toBytes(Buffer.from(storedChallenge).toString('hex'))`
 * — hex-encoding then hex-decoding the same bytes is a no-op, so this is
 * equivalent to signing `Buffer.from(challenge, 'utf-8')` directly). A
 * client that signs the raw random bytes the challenge hex represents,
 * instead of the string itself, fails verification — the exact mistake
 * this comment exists to prevent here.
 */
const nacl = require('tweetnacl')

function toHex(bytes) {
  return Buffer.from(bytes).toString('hex')
}

// Artillery 2.x detects an async function's arity and awaits it directly
// (no `done` callback) — declaring one anyway and calling it produced
// "done is not a function" here, since Artillery only passes
// (context, events) for a 2-argument async function.
async function setupAuthenticatedUser(context, events) {
  const target = 'http://localhost:3000'
  const keyPair = nacl.sign.keyPair()
  const publicKey = toHex(keyPair.publicKey)

  try {
    await fetch(`${target}/v1/identity/participants`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ publicKey, displayName: `loadtest-${publicKey.slice(0, 8)}` }),
    })

    const challengeRes = await fetch(`${target}/v1/identity/challenge`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ publicKey }),
    })
    const { data: challengeData } = await challengeRes.json()
    const challenge = challengeData.challenge

    // Sign the UTF-8 bytes of the challenge string itself — see file doc
    // comment above for why this specific encoding, not the raw bytes.
    const signature = nacl.sign.detached(Buffer.from(challenge, 'utf-8'), keyPair.secretKey)

    const authRes = await fetch(`${target}/v1/identity/authenticate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ publicKey, signature: toHex(signature) }),
    })
    const { data: authData } = await authRes.json()

    context.vars.sessionToken = authData.sessionToken
    context.vars.publicKey = publicKey
  } catch (err) {
    events.emit('error', `setupAuthenticatedUser failed: ${err.message}`)
  }
}

// chat-ws.yml's connect.function — picks a session from the pool
// pregenerate-users.js wrote, rather than authenticating fresh per VU.
// Required, not just a convenience: the ws engine only honors `connect`
// as scenarioSpec[0] (see pregenerate-users.js's doc comment), so an
// async HTTP auth flow can't run as an earlier flow step here the way
// it does for the http engine in intent-api.yml.
function pickChatSession(wsArgs, context, callback) {
  // Lazy require, not top-level: intent-api.yml shares this processor
  // file and must keep working even when users.json (chat-ws.yml's
  // prerequisite, generated by pregenerate-users.js) hasn't been created.
  let users
  try {
    users = require('./users.json')
  } catch {
    return callback(new Error('loadtest/users.json not found — run `node loadtest/pregenerate-users.js` first'))
  }
  const user = users[Math.floor(Math.random() * users.length)]
  wsArgs.target = `ws://localhost:3000/v1/openp2p/chat?token=${user.sessionToken}`
  return callback(null)
}

module.exports = { setupAuthenticatedUser, pickChatSession }
